### ISSUE TITLE
Filter Error 

### ISSUE THREAD

**Issue by okwilliamson** [UrbanInstitute/education-data-summary-endpoints#3]
This is my code chunk:
df4 <- get_education_data_summary(
    level = "school-districts",
    source = "ccd",
    topic = "enrollment",
    stat = "sum",
    var = "enrollment",
    by = "race",
    filters = list((state_leaid = '37'), (race = c(1,2,3,4,5,6,7,99)), (grade =c (-1,0,1,2,3,4,5,6,7,8,9,10,11,12)), (year = 2021))
    )

I only want NC student data (37), for all races and total, for pk-12 grades, and from 2021.

**Comment by erika-tyagi** [comment]
Thanks for getting in touch @okwilliamson! This will pull 2021 NC student enrollment data broken out by race and grade. 
```
df <- get_education_data_summary(
    level = "school-districts",
    source = "ccd",
    topic = "enrollment",
    stat = "sum",
    var = "enrollment",
    by = c("race", "grade"),  
    filters = list(
        state_location = "NC", 
        year = 2021
    )
)
```

From there, you should be able to filter to the grade levels that you're interested in. Let me know if I'm misunderstanding what you're looking for!

**Comment by okwilliamson** [comment]
Thank you, that worked!
